name: Deploy

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - 'opened'
      - 'reopened'
      - 'auto_merge_enabled'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.3

      - run: pnpm i

      - name: Build
        run: pnpm run playground-build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playground/dist
